const mongoose = require("mongoose");

const userSchema = new mongoose.Schema({
    first_name : {type: String, default: null},
    middle_name : {type: String, default: null},
    last_name : {type: String, default: null},
    family_name : {type: String, default: null},
    email: {type: String, default: null},
    password:{type: String},
    token:{type: String},
    phone_no:{type: String},
    comapany_name:{type: String},
    company_type:{type: String},
    pan:{type: String},
    gst: {type: String},
    address_1: {type: String},
    address_2: {type: String},
    landmark: {type: String},
    country: {type: String},
    state: {type: String},
    city: {type: String},
    pincode: {type: String},
    account_holder: {type: String},
    account_number: {type: String},
    account_type: {type: String},
    bank_name: {type: String},
    ifsc_code: {type: String},
    branch_name: {type: String},
    bank_address: {type: String},
    company_website: {type: String},
    company_size: {type: String},
    about: {type: String},
    research_method: {type: String},
    available_language: {type: String},
    research_location: {type: String},
    maximum_distance: {type: String},
    quota_per_day: {type: Number},
})

module.exports = mongoose.model("user", userSchema);